rain_rate_32bit: 'float32'
rain_accumulated_32bit: 'float32'
weather_code_SYNOP_4680: 'uint32'
weather_code_SYNOP_4677: 'uint32'
weather_code_METAR_4678: 'object'
weather_code_NWS: 'object'
reflectivity_32bit: 'float32'
mor_visibility: 'uint16'
sample_interval: 'uint16'
laser_amplitude: 'uint32'
n_particles: 'uint32'
sensor_temperature: 'int8'
sensor_serial_number: 'object'
firmware_iop: 'object'
firmware_dsp: 'object'
sensor_heating_current: 'float32'
sensor_battery_voltage: 'float32'
sensor_status: 'uint8'
start_time: 'object'
sensor_time: 'object'
sensor_date: 'object'
station_name: 'object'
station_number: 'object'
rain_amount_absolute_32bit: 'float32'
error_code: 'uint8'
sensor_temperature_PCB: 'int8'
sensor_temperature_right: 'int8'
sensor_temperature_left: 'int8'
rain_rate_16bit_30: 'float32'
rain_rate_16bit_1200: 'float32'
rain_accumulated_16bit: 'float32'
reflectivity_16bit: 'float32'
rain_kinetic_energy: 'float32'
snowfall_intensity: 'float32'
n_particles_all: 'uint32'
list_particles: 'object'
FieldN: 'object'
FieldV: 'object'
RawData: 'object'

