rain_rate_32bit: 'mm/h'
rain_accumulated_32bit: 'mm'
weather_code_SYNOP_4680: ''
weather_code_SYNOP_4677: ''
weather_code_METAR_4678: ''
weather_code_NWS: ''
reflectivity_32bit: 'dBz'
mor_visibility: 'm'
sample_interval: 's'
laser_amplitude: ''
n_particles: ''
sensor_temperature: 'degree celsius'
sensor_serial_number: ''
firmware_iop: ''
firmware_dsp: ''
sensor_heating_current: 'A'
sensor_battery_voltage: 'V'
sensor_status: ''
start_time: ''
sensor_time: ''
sensor_date: ''
station_name: ''
station_number: ''
rain_amount_absolute_32bit: 'mm'
error_code: ''
sensor_temperature_PCB: 'degree celsius'
sensor_temperature_right: 'degree celsius'
sensor_temperature_left: 'degree celsius'
rain_rate_16bit_30: 'mm/h'
rain_rate_16bit_1200: 'mm/h'
rain_accumulated_16bit: 'mm'
reflectivity_16bit: 'dBz'
rain_kinetic_energy: 'J/(m**2*h)'
snowfall_intensity: 'mm/h'
n_particles_all: ''
list_particles: ''
FieldN: 'log10 1/(m3*mm)'
FieldV: 'm/s'
RawData: ''

