'01': rain_rate_32bit
'02': rain_accumulated_32bit
'03': weather_code_SYNOP_4680
'04': weather_code_SYNOP_4677
'05': weather_code_METAR_4678
'06': weather_code_NWS
'07': reflectivity_32bit
'08': mor_visibility
'09': sample_interval
'10': laser_amplitude
'11': n_particles
'12': sensor_temperature
'13': sensor_serial_number
'14': firmware_iop
'15': firmware_dsp
'16': sensor_heating_current
'17': sensor_battery_voltage
'18': sensor_status
'19': start_time
'20': sensor_time
'21': sensor_date
'22': station_name
'23': station_number
'24': rain_amount_absolute_32bit
'25': error_code
'26': sensor_temperature_PCB
'27': sensor_temperature_right
'28': sensor_temperature_left
'30': rain_rate_16bit_30
'31': rain_rate_16bit_1200
'32': rain_accumulated_16bit
'33': reflectivity_16bit
'34': rain_kinetic_energy
'35': snowfall_intensity
'60': n_particles_all
'61': list_particles
'90': FieldN
'91': FieldV
'93': RawData
