'01': rain_rate_32bit
'02': rain_accumulated_32bit
'03': weather_code_SYNOP_4680
'04': weather_code_SYNOP_4677
'05': weather_code_METAR_4678
'06': weather_code_NWS
'07': reflectivity_32bit
'08': mor_visibility
'09': sample_interval
'10': laser_amplitude
'11': n_particles
'12': sensor_temperature
'13': sensor_serial_number
'14': firmware_iop
'15': firmware_dsp
'16': sensor_heating_current
'17': sensor_battery_voltage
'18': sensor_status
'19': start_time
'20': sensor_time
'21': sensor_date
'22': station_name
'23': station_number
'24': rain_amount_absolute_32bit
'25': error_code
'30': rain_rate_16bit
'31': rain_rate_12bit
'32': rain_accumulated_16bit
'33': reflectivity_16bit
'90': ND
'91': VD
'93': N
