rain_rate_32bit: 'mm/h'
rain_accumulated_32bit: 'mm'
weather_code_SYNOP_4680: ''
weather_code_SYNOP_4677: ''
weather_code_METAR_4678: ''
weather_code_NWS: ''
reflectivity_32bit: 'dBz'
mor_visibility: 'm'
sample_interval: 's'
laser_amplitude: ''
n_particles: ''
sensor_temperature: degree celsius
sensor_serial_number: ''
firmware_iop: ''
firmware_dsp: ''
sensor_heating_current: 'A'
sensor_battery_voltage: 'V'
sensor_status: ''
start_time: ''
sensor_time: ''
sensor_date: ''
station_name: ''
station_number: ''
rain_amount_absolute_32bit: 'mm'
error_code: ''
rain_rate_16bit: 'mm/h'
rain_rate_12bit: 'mm/h'
rain_accumulated_16bit: 'MM'
reflectivity_16bit: 'dBZ'
FieldN: '1/(m3*mm)'
FieldV: 'm/s'
RawData: ''
