rain_rate_32bit: 'Rainfall rate'
rain_accumulated_32bit: 'Accumulated rain amount over the measurement interval'
weather_code_SYNOP_4680: 'SYNOP weather code according to table 4680 of Parsivel documentation'
weather_code_SYNOP_4677: 'SYNOP weather code according to table 4677 of Parsivel documentation'
weather_code_METAR_4678: 'METAR/SPECI weather code according to table 4678 of Parsivel documentation'
weather_code_NWS: 'NWS weather code according to Parsivel documentation'
reflectivity_32bit: 'Radar reflectivity'
mor_visibility: 'Meteorological Optical Range in precipitation'
sample_interval: ''
laser_amplitude: 'Signal amplitude of the laser strip. A way to monitor if windows are dirty or not.'
n_particles: 'Number of particles detected and validated'
sensor_temperature: 'Temperature in sensor housing'
sensor_serial_number: ''
firmware_iop: ''
firmware_dsp: ''
sensor_heating_current: 'Sensor head heating current. Optimum heating output of the sensor head heating system can be guaranteed with a power supply voltage > 20 V '
sensor_battery_voltage:  'Power supply voltage'
sensor_status: 'Sensor status'
start_time: ''
sensor_time: ''
sensor_date: ''
station_name: ''
station_number: ''
rain_amount_absolute_32bit: 'Accumulated rain amount over the measurement interval'
error_code: 'Error code'
rain_rate_16bit: 'Rainfall rate'
rain_rate_12bit: 'Rainfall rate'
rain_accumulated_16bit: 'Accumulated rain amount over the measurement interval'
reflectivity_16bit: 'Radar reflectivity'
ND: 'Particle number concentrations per diameter class'
VD: 'Average particle velocities for each diameter class'
N: 'Drop counts per diameter and velocity class'
