start_identifier: 'uint8'
device_address: 'uint8'
sensor_serial_number: 'uint16'
software_version: 'float16'
date_sensor: 'object'
time_sensor: 'object'
  
###

weather_code_synop_4677_5min: 'uint8'
weather_code_synop_4680_5min: 'uint8'
weather_code_metar_4678_5min: 'object'
precipitation_rate_5min: 'float32'
weather_code_synop_4677: 'uint8'
weather_code_synop_4680: 'uint8'
weather_code_metar_4678: 'object'
precipitation_rate: 'float32'
rainfall_rate: 'float32'
snowfall_rate: 'float32'
precipitation_accumulated: 'float32'
mor_visibility: 'uint16'
reflectivity: 'float16'
quality_index: 'uint8'
max_hail_diameter: 'float16'
  
### Status

laser_status: 'uint8'
static_signal: 'uint8'


laser_temperature_analog_status: 'uint8'
laser_temperature_digital_status: 'uint8'
laser_current_analog_status: 'uint8'
laser_current_digital_status: 'uint8'
  
### Heating: glass(panes), housing, heads, carriers

sensor_voltage_supply_status: 'uint8'

current_heating_pane_transmitter_head_status: 'uint8'
current_heating_pane_receiver_head_status: 'uint8'

temperature_sensor_status: 'uint8'

current_heating_voltage_supply_status: 'uint8'
current_heating_house_status: 'uint8'
current_heating_heads_status: 'uint8'
current_heating_carriers_status: 'uint8'

control_output_laser_power_status: 'uint8'
reserve_status: 'uint8'

### Values

temperature_interior: 'uint16'

laser_temperature: 'uint8'
laser_current_average: 'uint16'

control_voltage: 'object'
optical_control_voltage_output: 'uint16'

sensor_voltage_supply: 'uint16'

current_heating_pane_transmitter_head: 'uint16'
current_heating_pane_receiver_head: 'uint16'

temperature_ambient: 'float32'

current_heating_voltage_supply: 'uint16'
current_heating_house: 'uint16'
current_heating_heads: 'uint16'
current_heating_carriers: 'uint16'

number_particles: 'uint32'
number_particles_internal_data: 'float32'
number_particles_min_speed: 'uint32'
number_particles_min_speed_internal_data: 'float32'
number_particles_max_speed: 'uint32'
number_particles_max_speed_internal_data: 'float32'
number_particles_min_diameter: 'uint32'
number_particles_min_diameter_internal_data: 'float32'
number_particles_no_hydrometeor: 'uint32'
number_particles_no_hydrometeor_internal_data: 'float32'
number_particles_unknown_classification: 'uint32'
number_particles_unknown_classification_internal_data: 'float32'

number_particles_class_1: 'uint32'
number_particles_class_1_internal_data: 'float32'
number_particles_class_2: 'uint32'
number_particles_class_2_internal_data: 'float32'
number_particles_class_3: 'uint32'
number_particles_class_3_internal_data: 'float32'
number_particles_class_4: 'uint32'
number_particles_class_4_internal_data: 'float32'
number_particles_class_5: 'uint32'
number_particles_class_5_internal_data: 'float32'
number_particles_class_6: 'uint32'
number_particles_class_6_internal_data: 'float32'
number_particles_class_7: 'uint32'
number_particles_class_7_internal_data: 'float32'
number_particles_class_8: 'uint32'
number_particles_class_8_internal_data: 'float32'
number_particles_class_9: 'uint32'
number_particles_class_9_internal_data: 'float32'
raw_spectrum: 'object'
diameter_speed: 'uint16'



























































