'01': start_identifier
'02': device_address
'03': sensor_serial_number
'04': firmware_DSP
'05': date_sensor
'06': time_sensor
'07': synop_4677_5min_weather_code
08: synop_4680_5min_weather_code
09: metar_4678_5min_weather_code
'10': intensity_total_5min
'11': synop_4677_weather_code
'12': synop_4680_weather_code
'13': metar_4678_weather_code
'14': intensity_total
'15': intensity_liquid
'16': intensity_solid
'17': accum_precip
'18': maximum_visibility
'19': radar_reflectivity
'20': quality_measurement
'21': max_diameter_hail
'22': laser_status
'23': static_signal
'24': laser_temperature_analog_status
'25': laser_temperature_digital_status
'26': laser_current_analog_status
'27': laser_current_digital_status
'28': sensor_status
'29': pane_heating_laser_head_current
'30': pane_heating_receiver_head_current
'31': temperature_sensor_status
'32': status_heating
'33': heating_house_current_status
'34': heating_heads_current_status
'35': heating_carriers_current_status
'36': control_output_laser_power_status
'37': reserve_status
'38': interior_temperature
'39': laser_temperature
'40': mean_laser_current
'41': control_voltage
'42': optical_control_output
'43': voltage_sensor_supply
'44': pane_heating_laser_head_current
'45': pane_heating_receiver_head_current
'46': ambient_temperature
'47': voltage_heating_supply
'48': heating_house_current
'49': heating_heads_current
'50': heating_carriers_current
'51': number_particles
'52': number_particles_internal_data
'53': number_particles_min_speed
'54': number_particles_min_speed_internal_data
'55': number_particles_max_speed
'56': number_particles_max_speed_internal_data
'57': number_particles_min_diameter
'58': number_particles_min_diameter_internal_data
'59': number_particles_no_hydrometeor
'60': number_particles_no_hydrometeor_internal_data
'61': number_particles_no_classification
'62': number_particles_no_classification_internal_data
'63': number_particles_class_1
'64': number_particles_class_1_internal_data
'65': number_particles_class_2
'66': number_particles_class_2_internal_data
'67': number_particles_class_3
'68': number_particles_class_3_internal_data
'69': number_particles_class_4
'70': number_particles_class_4_internal_data
'71': number_particles_class_5
'72': number_particles_class_5_internal_data
'73': number_particles_class_6
'74': number_particles_class_6_internal_data
'75': number_particles_class_7
'76': number_particles_class_7_internal_data
'77': number_particles_class_8
'78': number_particles_class_8_internal_data
'79': number_particles_class_9
'80': number_particles_class_9_internal_data
'81': precipitation_spectrum
'520': diameter_speed
